### ISSUE TITLE
getStreamUri doesn't connect to sub stream of Onvif camera 

### ISSUE THREAD

**Issue by bubblesdev** [faithoflifedev/easy_onvif#57]
Hi there!
I'm having difficulty in connecting to the substream of Onvif device. Such that it throws Dio exception while making the request which it makes difficult to debug as it comes from the package itself. Kindly look into this issue pls.
Thank you for your feedback

**Comment by faithoflifedev** [comment]
Hi @bubblesdev ,

Some tips on how to get help with an issue:

- Read through the previous [issues](https://github.com/faithoflifedev/easy_onvif/issues?q=is%3Aissue) and you might find some tips on how to debug yours take a read through this [one](https://github.com/faithoflifedev/easy_onvif/issues/54)
- Supply some sample code that can be used to recreate the issue
- Provide the stacktrace with the error your seeing

Without these as a minimum there's not much help anyone can provide.

**Comment by bubblesdev** [comment]
Thnks but i have gone through previous issues but no related ones.
<img width="1110" alt="Screen Shot 2024-02-16 at 19 55 40" src="https://github.com/faithoflifedev/easy_onvif/assets/73842287/7fd6b6be-d1e3-400f-b6c4-b22ecd7f5ab8">
It throws the error in the screenshot above when connecting to the sub stream of an onvif and it connect to the main stream. Here's a screenshot of the profile in the device from onvifer application.

![IMG_5164](https://github.com/faithoflifedev/easy_onvif/assets/73842287/6f39e834-64a6-4d88-bedf-0c4c3ed78e56)
I can't debug exactly why it is not processing the request. I hope this helps!

**Comment by faithoflifedev** [comment]
Hi @bubblesdev, 

If you install and Configure the [cli tools](https://github.com/faithoflifedev/easy_onvif/blob/main/bin/README.md) provided by the package you can get information back from your camera that can be very useful for debugging.

Your stated issue is "I'm having difficulty in connecting to the substream of Onvif device.".  Since this package only covers the protocols and spec of Onvif, it provided no code that allows you to actually "connect" with a stream.  It does provide the means to you to determine the `uri` of a stream which you could feed to some other tool to connect.

Once you've got the cli tools configured and working, then you could run a command like:
```sh
#Where Profile_2 is the profile token of the substream
onvif media1  get-stream-uri -t Profile_2
```
The command will output the `uri` for the stream along with some other info.

As mentioned earlier, unless you can provide some simple code that can be used to recreate your issue, then there's not much help that can be offered.  Also if the problem is outside the scope of this tool set, you'll have to look outside for help.
